apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:2028
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
      queryTimeout: 60s
      timeInterval: 15s
    secureJsonData: {}
    version: 1
